from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
import pytest

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.config import Columns


@pytest.fixture()
def sample_rtt_df() -> pd.DataFrame:
    rows = [
        {
            Columns.PERIOD: "2024-01",
            Columns.PROVIDER_ORG_CODE: "A",
            Columns.PROVIDER_ORG_NAME: "Alpha Trust",
            Columns.COMMISSIONER_ORG_NAME: "North ICB",
            Columns.RTT_PART_TYPE: "Part_2",
            Columns.TREATMENT_FUNCTION_CODE: "C_999",
            Columns.TREATMENT_FUNCTION_NAME: "All specialties",
            Columns.TOTAL_WAITING: 100,
            Columns.WITHIN_18_WEEKS: 80,
            Columns.OVER_52_WEEKS: 5,
        },
        {
            Columns.PERIOD: "2024-01",
            Columns.PROVIDER_ORG_CODE: "A",
            Columns.PROVIDER_ORG_NAME: "Alpha Trust",
            Columns.COMMISSIONER_ORG_NAME: "North ICB",
            Columns.RTT_PART_TYPE: "Part_2",
            Columns.TREATMENT_FUNCTION_CODE: "C_110",
            Columns.TREATMENT_FUNCTION_NAME: "Trauma and Orthopaedic Service",
            Columns.TOTAL_WAITING: 40,
            Columns.WITHIN_18_WEEKS: 30,
            Columns.OVER_52_WEEKS: 2,
        },
        {
            Columns.PERIOD: "2024-01",
            Columns.PROVIDER_ORG_CODE: "B",
            Columns.PROVIDER_ORG_NAME: "Bravo Trust",
            Columns.COMMISSIONER_ORG_NAME: "North ICB",
            Columns.RTT_PART_TYPE: "Part_2",
            Columns.TREATMENT_FUNCTION_CODE: "C_999",
            Columns.TREATMENT_FUNCTION_NAME: "All specialties",
            Columns.TOTAL_WAITING: 70,
            Columns.WITHIN_18_WEEKS: 35,
            Columns.OVER_52_WEEKS: 10,
        },
        {
            Columns.PERIOD: "2024-01",
            Columns.PROVIDER_ORG_CODE: "B",
            Columns.PROVIDER_ORG_NAME: "Bravo Trust",
            Columns.COMMISSIONER_ORG_NAME: "North ICB",
            Columns.RTT_PART_TYPE: "Part_2",
            Columns.TREATMENT_FUNCTION_CODE: "C_120",
            Columns.TREATMENT_FUNCTION_NAME: "General Surgery Service",
            Columns.TOTAL_WAITING: 20,
            Columns.WITHIN_18_WEEKS: 15,
            Columns.OVER_52_WEEKS: 1,
        },
        {
            Columns.PERIOD: "2024-02",
            Columns.PROVIDER_ORG_CODE: "A",
            Columns.PROVIDER_ORG_NAME: "Alpha Trust",
            Columns.COMMISSIONER_ORG_NAME: "North ICB",
            Columns.RTT_PART_TYPE: "Part_2",
            Columns.TREATMENT_FUNCTION_CODE: "C_999",
            Columns.TREATMENT_FUNCTION_NAME: "All specialties",
            Columns.TOTAL_WAITING: 120,
            Columns.WITHIN_18_WEEKS: 90,
            Columns.OVER_52_WEEKS: 6,
        },
        {
            Columns.PERIOD: "2024-02",
            Columns.PROVIDER_ORG_CODE: "A",
            Columns.PROVIDER_ORG_NAME: "Alpha Trust",
            Columns.COMMISSIONER_ORG_NAME: "North ICB",
            Columns.RTT_PART_TYPE: "Part_2",
            Columns.TREATMENT_FUNCTION_CODE: "C_999",
            Columns.TREATMENT_FUNCTION_NAME: "All specialties",
            Columns.TOTAL_WAITING: 30,
            Columns.WITHIN_18_WEEKS: 20,
            Columns.OVER_52_WEEKS: 2,
        },
        {
            Columns.PERIOD: "2024-02",
            Columns.PROVIDER_ORG_CODE: "A",
            Columns.PROVIDER_ORG_NAME: "Alpha Trust",
            Columns.COMMISSIONER_ORG_NAME: "North ICB",
            Columns.RTT_PART_TYPE: "Part_2",
            Columns.TREATMENT_FUNCTION_CODE: "C_110",
            Columns.TREATMENT_FUNCTION_NAME: "Trauma and Orthopaedic Service",
            Columns.TOTAL_WAITING: 60,
            Columns.WITHIN_18_WEEKS: 45,
            Columns.OVER_52_WEEKS: 3,
        },
        {
            Columns.PERIOD: "2024-02",
            Columns.PROVIDER_ORG_CODE: "A",
            Columns.PROVIDER_ORG_NAME: "Alpha Trust",
            Columns.COMMISSIONER_ORG_NAME: "North ICB",
            Columns.RTT_PART_TYPE: "Part_2",
            Columns.TREATMENT_FUNCTION_CODE: "C_110",
            Columns.TREATMENT_FUNCTION_NAME: "Trauma and Orthopaedic Service",
            Columns.TOTAL_WAITING: 20,
            Columns.WITHIN_18_WEEKS: 15,
            Columns.OVER_52_WEEKS: 1,
        },
        {
            Columns.PERIOD: "2024-02",
            Columns.PROVIDER_ORG_CODE: "B",
            Columns.PROVIDER_ORG_NAME: "Bravo Trust",
            Columns.COMMISSIONER_ORG_NAME: "North ICB",
            Columns.RTT_PART_TYPE: "Part_2",
            Columns.TREATMENT_FUNCTION_CODE: "C_999",
            Columns.TREATMENT_FUNCTION_NAME: "All specialties",
            Columns.TOTAL_WAITING: 80,
            Columns.WITHIN_18_WEEKS: 40,
            Columns.OVER_52_WEEKS: 12,
        },
        {
            Columns.PERIOD: "2024-02",
            Columns.PROVIDER_ORG_CODE: "B",
            Columns.PROVIDER_ORG_NAME: "Bravo Trust",
            Columns.COMMISSIONER_ORG_NAME: "North ICB",
            Columns.RTT_PART_TYPE: "Part_2",
            Columns.TREATMENT_FUNCTION_CODE: "C_120",
            Columns.TREATMENT_FUNCTION_NAME: "General Surgery Service",
            Columns.TOTAL_WAITING: 30,
            Columns.WITHIN_18_WEEKS: 18,
            Columns.OVER_52_WEEKS: 4,
        },
        {
            Columns.PERIOD: "2024-02",
            Columns.PROVIDER_ORG_CODE: "C",
            Columns.PROVIDER_ORG_NAME: "Charlie Trust",
            Columns.COMMISSIONER_ORG_NAME: "North ICB",
            Columns.RTT_PART_TYPE: "Part_2",
            Columns.TREATMENT_FUNCTION_CODE: "C_999",
            Columns.TREATMENT_FUNCTION_NAME: "All specialties",
            Columns.TOTAL_WAITING: 50,
            Columns.WITHIN_18_WEEKS: 25,
            Columns.OVER_52_WEEKS: 5,
        },
        {
            Columns.PERIOD: "2024-02",
            Columns.PROVIDER_ORG_CODE: "C",
            Columns.PROVIDER_ORG_NAME: "Charlie Trust",
            Columns.COMMISSIONER_ORG_NAME: "North ICB",
            Columns.RTT_PART_TYPE: "Part_2",
            Columns.TREATMENT_FUNCTION_CODE: "C_120",
            Columns.TREATMENT_FUNCTION_NAME: "General Surgery Service",
            Columns.TOTAL_WAITING: 10,
            Columns.WITHIN_18_WEEKS: 5,
            Columns.OVER_52_WEEKS: 1,
        },
        {
            Columns.PERIOD: "2024-02",
            Columns.PROVIDER_ORG_CODE: "D",
            Columns.PROVIDER_ORG_NAME: "Delta Trust",
            Columns.COMMISSIONER_ORG_NAME: "South ICB",
            Columns.RTT_PART_TYPE: "Part_2",
            Columns.TREATMENT_FUNCTION_CODE: "C_999",
            Columns.TREATMENT_FUNCTION_NAME: "All specialties",
            Columns.TOTAL_WAITING: 40,
            Columns.WITHIN_18_WEEKS: 20,
            Columns.OVER_52_WEEKS: 2,
        },
        {
            Columns.PERIOD: "2024-02",
            Columns.PROVIDER_ORG_CODE: "D",
            Columns.PROVIDER_ORG_NAME: "Delta Trust",
            Columns.COMMISSIONER_ORG_NAME: "South ICB",
            Columns.RTT_PART_TYPE: "Part_2",
            Columns.TREATMENT_FUNCTION_CODE: "C_110",
            Columns.TREATMENT_FUNCTION_NAME: "Trauma and Orthopaedic Service",
            Columns.TOTAL_WAITING: 15,
            Columns.WITHIN_18_WEEKS: 12,
            Columns.OVER_52_WEEKS: 1,
        },
        {
            Columns.PERIOD: "2024-02",
            Columns.PROVIDER_ORG_CODE: "A",
            Columns.PROVIDER_ORG_NAME: "Alpha Trust",
            Columns.COMMISSIONER_ORG_NAME: "North ICB",
            Columns.RTT_PART_TYPE: "Part_1A",
            Columns.TREATMENT_FUNCTION_CODE: "C_110",
            Columns.TREATMENT_FUNCTION_NAME: "Trauma and Orthopaedic Service",
            Columns.TOTAL_WAITING: 999,
            Columns.WITHIN_18_WEEKS: 999,
            Columns.OVER_52_WEEKS: 0,
        },
    ]
    dataframe = pd.DataFrame(rows)
    dataframe[Columns.PERIOD_DT] = pd.to_datetime(
        dataframe[Columns.PERIOD],
        format="%Y-%m",
    )
    return dataframe
